services:
  postgres:
    image: postgres:14-alpine
    env_file: backend/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lizakobzeva -d dating_bot"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file: backend/.env
    depends_on:
      postgres:
        condition: service_healthy

  bot:
    build: ./bot
    env_file: bot/.env
    depends_on:
      - backend

volumes:
  pgdata:
